For v_ghost use v's type instead of this's type
libMesh/libmesh pull request #2980
Opened 2021-08-12 20:07 UTC by lindsayad

If this was ghosted and v was parallel, then pre this PR you would
get a seg-fault because the local representation of a parallel
vector is NULL

Refs #2785

2021-08-12 20:26 UTC, fdkong requested changes

2021-08-12 20:26 UTC, fdkong commented on src/numerics/petsc_vector.C
> +  VecGhostLocalFormRAII<T> v_ghost(*v, v->type() == GHOSTED);
There are several other places where the same issue may exist. Could you fix other places as well?

2021-08-12 20:46 UTC, jwpeterson commented
Crap, it looks like I broke this in 6d51e68bf50105629d24df4adb78fd3005cfd9ca. Your fix looks good to me though :+1:

2021-08-12 20:47 UTC, jwpeterson approved these changes

2021-08-12 21:01 UTC, roystgnr approved these changes

2021-08-12 21:04 UTC, roystgnr requested changes
Actually ... the code certainly *looks* obviously correct here, and I just assumed someone had let some thread-unsafe code slip into MOOSE ... but those errors all look like PETSc Vec related errors.  What's going on there?

2021-08-12 21:07 UTC, lindsayad commented
Wow yea MOOSE no likey

2021-08-12 21:16 UTC, lindsayad commented
Hmm yea it seems like @jwpeterson 's new code perfectly emulated the old code. I guess just we've never supported doing this `add` overload when `this` is ghosted and `v` is parallel? And if this is not the fix to support that, then I'll have to expand my PETSc knowledge

2021-08-12 21:23 UTC, jwpeterson commented
> perfectly emulated the old code.

Haha, yes I see now what I was doing was just replacing those enclosing `if`-`else` blocks with something equivalent... @fdkong: is attempting to get the local form of a PARALLEL vector really supposed to just give you back a `NULL` pointer? It seems like that could only ever end badly...

2021-08-12 21:37 UTC, lindsayad commented
Yea all the failures in MOOSE are for the opposite scenario: `this` is `PARALLEL` and `v` is `GHOSTED`. So yea the fact that my change incurred all those parallel failures makes total sense. When `this` is `PARALLEL` we definitely don't want to `add` with the local form of `v` (which is what my change did)

2021-08-12 21:39 UTC, lindsayad commented
I feel like what should be done when `this` is `GHOSTED` and `v` is `PARALLEL` is to do the `VecAXPY` *not* with the local forms and then to do `VecGhostUpdateBegin` and `VecGhostUpdateEnd` after... ?

2021-08-12 21:50 UTC, fdkong commented
>@fdkong: is attempting to get the local form of a PARALLEL vector really supposed to just give you back a NULL pointer? It seems like that could only ever end badly...

From my understanding, the local form is created only when we call VecCreateGhost/VecCreateGhostBlock or their friends. 

The local form will be a null pointer if we do not create a ghost vector

2021-08-12 21:51 UTC, lindsayad commented
You might say that if you don't create a ghost, then the local form is truly ethereal ... like a 👻

2021-08-12 22:14 UTC, jwpeterson commented
> I feel like what should be done when `this` is `GHOSTED` and `v` is `PARALLEL` is to do the `VecAXPY` _not_ with the local forms and then to do `VecGhostUpdateBegin` and `VecGhostUpdateEnd` after... ?

OK... so we would have to add an if-else check back in to handle that case? That's a bit annoying but not the end of the world I guess. Note also that there's a `VecGhostUpdateBeginEnd()` macro which can simplify that part a bit.

2021-08-12 22:19 UTC, lindsayad commented
I *think* the new commit should work for all cases and simplifies the code

2021-08-12 22:32 UTC, fdkong approved these changes
The code looks so beautiful. 

I like these changes.

2021-08-13 15:53 UTC, jwpeterson commented
So can `VecGhostLocalFormRAII` just be done away with completely? I'm not sure I see the point of it now. It looks like `PetscVector<T>::scale`, `abs()`, and `operator=(T)` still use it, but do they need to?

2021-08-16 14:43 UTC, roystgnr approved these changes

2021-08-18 22:39 UTC, merged