Switch from deprecated sprintf to snprintf
libMesh/libmesh pull request #3434
Opened 2022-11-08 20:36 UTC by loganharbour

Closes #3433

2022-11-08 21:39 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1228015/) on ce46e8d wanted to post the following:


## Coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>7bbcc3</th>
      <th colspan=4>#3434 ce46e8</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>59.63%</td>
      <td>59.63%</td>
      <td>-</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>48033</td>
      <td>48033</td>
      <td>-</td>
      <td>8</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>32525</td>
      <td>32525</td>
      <td>-</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/libmesh/docs/PRs/3434/coverage_diff)

[Full coverage report](https://mooseframework.inl.gov/libmesh/docs/PRs/3434/coverage)



This comment will be updated on new commits.

2022-11-08 21:58 UTC, roystgnr requested changes

2022-11-08 22:19 UTC, jwpeterson commented on src/systems/system_io.C
> +        std::snprintf(buf, 80, "%s", this->variable_name(var).c_str());
I agree we should use C++ solutions here, but this is also a free PR that I didn't have to do anything for...

2022-11-08 22:50 UTC, roystgnr commented on src/systems/system_io.C
> +        std::snprintf(buf, 80, "%s", this->variable_name(var).c_str());
Yeah, I know, gift horse, mouth.  I'll rewrite the PR myself to get it cleaned up, I just want to be sure first that there isn't some reason it wasn't cleaned up to begin with.  It makes me suspicious to see longer code where shorter code would have worked better, like there must be something I'm missing.

2022-11-08 23:38 UTC, loganharbour commented on src/systems/system_io.C
> +        std::snprintf(buf, 80, "%s", this->variable_name(var).c_str());
This was just my bare-minimum fix so that I could properly compile with Werror on my machine for other development :-)

2022-11-11 16:13 UTC, jwpeterson commented
Closing in favor of #3438

2022-11-11 16:13 UTC, closed without merging