Allow boundary be associated with child elements
libMesh/libmesh pull request #3470
Opened 2023-01-25 17:46 UTC by dewenyushu

Taking over #3094

2023-01-25 18:43 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1317008/) on b6b8849 wanted to post the following:


## Coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>482ca3</th>
      <th colspan=4>#3470 b6b884</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>59.96%</td>
      <td>59.94%</td>
      <td>-0.01%</td>
      <td>38.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>48759</td>
      <td>48770</td>
      <td>+11</td>
      <td>19</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>32563</td>
      <td>32590</td>
      <td>+27</td>
      <td>31</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/libmesh/docs/PRs/3470/coverage_diff)

[Full coverage report](https://mooseframework.inl.gov/libmesh/docs/PRs/3470/coverage)

## Warnings

- New new line coverage rate 38.00% is less than the suggested 90.0%



This comment will be updated on new commits.

2023-01-25 21:31 UTC, dewenyushu commented
@roystgnr I just tried to address your concerns for the original PR (#3094 ) here. Please let me know your comments. Appreciate it so much!

2023-01-26 22:15 UTC, dewenyushu commented on src/mesh/boundary_info.C
> +
Here is the function to transfer boundary to the parent before coarsening

2023-01-26 22:15 UTC, dewenyushu commented on src/mesh/mesh_refinement.C
> +      _mesh.get_boundary_info().transfer_boundary_ids_to_parent(elem);
Here is when I transfer the boundary info to the parent

2023-01-26 22:19 UTC, dewenyushu commented
I tried numerous times adding a unit test for this code change and it would not work.. Not sure if this is something related to the code change or related to the unit test (this is the first cpp unit test I am writing so..)

@roystgnr Would you mind taking a quick look and letting me know where I made mistakes that is obvious to you? Thanks!!

2023-01-30 13:48 UTC, roystgnr commented
> I tried numerous times adding a unit test for this code change and it would not work.

That's good!  The best unit tests are the ones that prevent regressions of bugs that have already happened.

I can replicate this; looking at it today.

2023-01-30 13:48 UTC, roystgnr commented
Oh, or maybe I should have refreshed the page first.  Looks like CI thinks you already fixed it.  Reviewing today, then.

2023-01-30 16:26 UTC, dewenyushu commented
> 

Great! Really appreciate it!! - I am not familiar with unit tests so please bare with me if there are some stupid mistakes

2023-01-30 16:26 UTC, dewenyushu commented
> > I tried numerous times adding a unit test for this code change and it would not work.
> 
> That's good! The best unit tests are the ones that prevent regressions of bugs that have already happened.
> 
> I can replicate this; looking at it today.

Great! Really appreciate it!! - I am not familiar with unit tests so please bare with me if there are some stupid mistakes

2023-02-01 22:57 UTC, roystgnr requested changes
We're getting closer, at least?

2023-02-01 22:57 UTC, roystgnr commented on tests/mesh/boundary_info.C
> +    std::unique_ptr<Mesh> mesh;
Just put the Mesh on the stack here?

But that's a quibble; this looks like an excellent first unit test.  Not yet *sufficient*, given the failure cases above, but a good start.

2023-02-21 16:36 UTC, dewenyushu commented
close this one due to #3477

2023-02-21 16:36 UTC, closed without merging