Impose BC on u instead of q in Raviart-Thomas example
libMesh/libmesh pull request #3664
Opened 2023-10-19 22:12 UTC by lindsayad

Error results for tris to be clear we're keeping the desired convergence rates:

grid = 4
L2 error is: 0.500032
HDiv semi-norm error is: 1.27137
HDiv error is: 1.36617
grid = 8
L2 error is: 0.251364
HDiv semi-norm error is: 0.643384
HDiv error is: 0.690743
grid = 16
L2 error is: 0.125855
HDiv semi-norm error is: 0.322662
HDiv error is: 0.346338
grid = 32
L2 error is: 0.0629499
HDiv semi-norm error is: 0.16145
HDiv error is: 0.173289
grid = 64
L2 error is: 0.0314776
HDiv semi-norm error is: 0.0807404
HDiv error is: 0.0866594

2023-10-19 22:16 UTC, lindsayad commented
New BC treatment:
- 93 iterations with ILU
- condition number: 2e1

Old BC treatment:
- 148 iterations with ILU
- condition number: 6e11

2023-10-19 22:24 UTC, roystgnr commented
I do like getting rid of penalty BCs ... but looking at the diff now, isn't this solving a different problem?  Before we were solving the PDE with Neumann BCs (on p, so they looked like Dirichlet BCs on u); now we're solving it with Dirichlet BCs on p.

2023-10-19 22:43 UTC, lindsayad commented
Previously we were weakly enforcing the condition:

<p, n * v> = <penalty * n * (u - u_exact), n * v>

Now we are weakly enforcing the condition:

<p, n * v> = <p_exact, n * v>

where p is the scalar solution field, v is the vector test function, and n is the normals.

We are weakly enforcing a condition based on the same term that falls out of integration by parts in the vector equation

2023-10-19 22:48 UTC, lindsayad commented
You can say that we're solving a different problem in the sense that we are involving p_exact instead of u_exact, but as we have an analytical relation between p_exact and u_exact, I don't really see them as very different. I believe that users in general will be more likely to know boundary information about the scalar solution field than the vector solution field so it makes sense to offer an example demonstrating such a case. Moreover, as shown by the diff, it's a simpler problem to implement. I can add another example if that is preferred

2023-10-20 00:28 UTC, roystgnr commented
> we have an analytical relation between p_exact and u_exact

Do you mean "we have an exact solution that we're comparing to, so we know both p_exact and u_exact from that", or do you mean "boundary conditions on p and boundary conditions on u are equivalent problems"?  Because the former isn't true for non-manufactured problems, and the latter just isn't true.

> as shown by the diff, it's a simpler problem to implement

This is certainly true, but that's because it's different problem.  The pure Neumann boundary-value problem residual has a non-trivial kernel, so we had to have a Lagrange multiplier to constrain it away; the pure Dirichlet boundary-value problem residual doesn't, so we don't.

> I believe that users in general will be more likely to know boundary information about the scalar solution field than the vector solution field

Users are likely to know boundaries' Dirichlet data in some cases, Neumann data in others, Robin data in others, and mixtures of all three in the general (even just the general linear!) case.

> so it makes sense to offer an example demonstrating such a case.

I definitely like this.  But when we were talking on Slack I misunderstood; it sounded like the proposed changes were "solve the same problem, just with something better than a penalty method", which seemed like a pure improvement.  "Solve an easier problem instead", less so.  We're adding one bit of code with didactic value and removing two others this way.

> I can add another example if that is preferred

It'd be my preference.  My first instinct is to just put both types of boundary conditions in this example, with Dirichlet on one or two sides and Neumann on the others.  But *any* Dirichlet boundary, even one point, makes the kernel trivial and the Lagrange multiplier pointless ... whereas I really liked the Lagrange multiplier example here.  I think this was the only pure-Neumann example we had.

2023-10-20 00:35 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1833601/) on 48f9378 wanted to post the following:


## Coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>4270c3</th>
      <th colspan=4>#3664 48f937</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>61.97%</td>
      <td>61.97%</td>
      <td>+0.00%</td>
      <td>-</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>67456</td>
      <td>67457</td>
      <td>+1</td>
      <td>0</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>41395</td>
      <td>41394</td>
      <td>-1</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/libmesh/docs/PRs/3664/coverage_diff)

[Full coverage report](https://mooseframework.inl.gov/libmesh/docs/PRs/3664/coverage)



This comment will be updated on new commits.

2023-10-20 02:00 UTC, lindsayad commented
> Do you mean "we have an exact solution that we're comparing to, so we know both p_exact and u_exact from that", or do you mean "boundary conditions on p and boundary conditions on u are equivalent problems"? Because the former isn't true for non-manufactured problems, and the latter just isn't true.

I definitely meant the former. Yes you are right, the former is not true for non-manufactured problems, but this is a manufactured problem which is why I said it.

> We're adding one bit of code with didactic value and removing two others this way.

Yea, maybe we can just leave this example as-is. Or I can add a boolean flag to toggle between the two within this single example

2023-10-20 14:22 UTC, roystgnr commented
> Or I can add a boolean flag to toggle between the two within this single example

Oh, I'd love that.

2023-10-20 19:00 UTC, nmnobre requested changes
Hi both, sorry for the delayed response.

I agree with everything that has been said, I'd also prefer to see an addition to the example instead of a simple replacement.
I'd say illustrating two alternative formulations producing the same results is actually of enormous didactic value.
Specially in this case, where both BCs are (or look like) Dirichlet, just on different fields.

Since you seem to be happy to add a boolean flag to switch between formulations, I'll mark this as "Request changes". :)

2023-10-23 11:08 UTC, nmnobre reviewed
Hi Alex, this is very nice, thank you! :)

Could you please update `doc/html/examples/vector_fe_ex6.html`? I think that's the only thing that absolutely needs doing, the other stuff is just me nit-picking... You can also add yourself as an author of this example. :)

2023-10-23 17:11 UTC, lindsayad commented on examples/vector_fe/vector_fe_ex6/vector_fe_ex6.C
> +                            Ke(i, j) += JxW_face[qp] * penalty * vector_phi_face[i][qp] *
Not quite sure what you mean. For instance the `RealGradient vector_value;` line in the Neumann branch is indented to column 22 and the `Real scalar_value;` line in the Dirichlet branch is also indented to column 22

2023-10-23 17:11 UTC, lindsayad commented on examples/vector_fe/vector_fe_ex6/vector_fe_ex6.C
> +                          Fe(i) += JxW_face[qp] * penalty * vector_phi_face[i][qp] * normals[qp] *
For me the `Fe(i) +=` lines in both Neumann and Dirichlet branches are indented to column 26. The `Ke` line in the Neumann branch, due to its nested `for`, is indented to column 28

2023-10-23 17:11 UTC, lindsayad commented on examples/vector_fe/vector_fe_ex6/vector_fe_ex6.C
> +                  else
I don't have a `dirichlet` boolean. In `main` we error if the user has selected something other than neumann or dirichlet so as of now there are only two possible states, so the states are coverable by the single `neumann` boolean

2023-10-23 17:17 UTC, lindsayad commented on examples/vector_fe/vector_fe_ex6/vector_fe_ex6.C
> +                          Fe(i) += JxW_face[qp] * penalty * vector_phi_face[i][qp] * normals[qp] *
Oh I understand what you're saying now... the spacing between operators

2023-10-23 17:23 UTC, lindsayad commented
> You can also add yourself as an author

Haha nah my contributions are relatively small. I think the author line is good as-is!

2023-10-23 19:02 UTC, roystgnr commented on examples/vector_fe/vector_fe_ex6/vector_fe_ex6.C
> +                  else
Yeah; if this was a real application we'd be testing bcids and putting Dirichlet on some and Neumann on others, but this is good for a simple example.

2023-10-23 19:02 UTC, roystgnr approved these changes

2023-10-23 19:03 UTC, roystgnr commented
I kicked the Test MOOSE debug recipe ... but I think that's the second time in a week I've seen a timeout there?  That worries me.

2023-10-23 20:23 UTC, nmnobre commented on examples/vector_fe/vector_fe_ex6/vector_fe_ex6.C
> +                      else
✅

2023-10-23 20:24 UTC, nmnobre commented on examples/vector_fe/vector_fe_ex6/vector_fe_ex6.C
> +          if (neumann)
✅

2023-10-23 20:24 UTC, nmnobre commented on examples/vector_fe/vector_fe_ex6/vector_fe_ex6.C
> +                            Ke(i, j) += JxW_face[qp] * penalty * vector_phi_face[i][qp] *
✅

2023-10-23 20:24 UTC, nmnobre commented on examples/vector_fe/vector_fe_ex6/vector_fe_ex6.C
> +                          Fe(i) += JxW_face[qp] * penalty * vector_phi_face[i][qp] * normals[qp] *
✅

2023-10-23 20:25 UTC, nmnobre commented on examples/vector_fe/vector_fe_ex6/vector_fe_ex6.C
> +  // Add a scalar Lagrange multiplier to remove the nullspace if imposing the Neumann condition
✅
Haha, and from a Portuguese 😝

2023-10-23 20:26 UTC, nmnobre commented on examples/vector_fe/vector_fe_ex6/vector_fe_ex6.C
> +  // Retrieve our boundary condition type. If not Neumann, then it is Dirichlet
✅

2023-10-23 20:26 UTC, nmnobre commented on examples/vector_fe/vector_fe_ex6/vector_fe_ex6.C
> +      // Dirichlet condition for u
✅

2023-10-23 20:31 UTC, nmnobre commented on examples/vector_fe/vector_fe_ex6/vector_fe_ex6.C
> +                  else
> I don't have a dirichlet boolean.

I know, I was trying to convince you to (even though it's obviously redundant). :)
Semantically the code is correct, and my suggestion wasn't meant as a fix, rather for readability, I was just nitpicking...

2023-10-23 20:34 UTC, nmnobre approved these changes
Small as they might be, I still think these changes are very valuable, so thank you! :)

2023-10-23 22:03 UTC, merged