Packing for libEigen dynamic matrices
libMesh/libmesh pull request #3673
Opened 2023-10-25 00:48 UTC by dschwen

Closes #3662

2023-10-26 03:15 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1843753/) on ceeb80b wanted to post the following:


## Coverage

Coverage did not change

[Full coverage report](https://mooseframework.inl.gov/libmesh/docs/PRs/3673/coverage)



This comment will be updated on new commits.

2023-11-01 01:41 UTC, roystgnr commented
Added some non-default recipes I'm skeptical about, but at first glance, modulo a few possible missing ifndefs, this is looking good.

2023-11-01 14:24 UTC, roystgnr requested changes
This looks like it's good to go as soon as the --disable-eigen case is fixed.

2023-11-01 14:24 UTC, roystgnr commented on include/parallel/parallel_eigen.h
> +// libEigen includes
Pretty much everything from here down ought to be wrapped in `#ifdef LIBMESH_HAVE_EIGEN`

2023-11-01 20:27 UTC, roystgnr commented
Ah, hell.  I should have merged yours before mine.  Mind fixing up or adding a new rebootstrap commit?

2023-11-02 16:24 UTC, dschwen commented
sure, no problem

2023-11-02 16:27 UTC, dschwen commented
I manually fixed the conflict

2023-11-03 02:41 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1859838/) on eca85e8 wanted to post the following:


The following coverage requirement(s) failed:
- Failed to generate coverage rate (required: 55.0%)

2023-11-03 03:14 UTC, roystgnr commented
Just the network issues with the python test again on `Test MOOSE mac`; this is good to go.

2023-11-03 03:14 UTC, merged