Streamline exact solution specification in Vector FE ex6
libMesh/libmesh pull request #3678
Opened 2023-10-28 01:11 UTC by nmnobre

Hey,

I decided to play a bit with #3676, and for that I defined a wavenumber-like variable to allow me to change the characteristics of the solution function easily. Other people might find this ability useful, this is for them.

Now, some examples read an input parameter, `extra_error_quadrature`, to adjust the quadrature order for error estimation purposes. From what I've seen, it's default value is often 2, which is not better than 1 (the new global default), and worse, induced me in error (this is perhaps my bad)... In libMesh, the quadrature order is the order of the highest polynomial which can be exactly integrated, not the number of points in the quadrature rule. As the default quadrature order is 2p+1, i.e. odd, adding an even number, m, as the extra order, is never better than just adding m-1. From what I've seen, all examples which take an input parameter to set the extra order use an even number as its default, and none of these examples need it anymore with the new global default. I do think having at least one example illustrating the parameter's existence is valuable, but I think we can get rid of it in most examples, thoughts?

2023-10-28 04:41 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1849647/) on ddc8f38 wanted to post the following:


## Coverage

Coverage did not change

[Full coverage report](https://mooseframework.inl.gov/libmesh/docs/PRs/3678/coverage)



This comment will be updated on new commits.

2023-10-30 18:06 UTC, lindsayad requested changes

2023-10-30 18:06 UTC, lindsayad commented on examples/vector_fe/vector_fe_ex6/div_grad_exact_solution.h
> +  const Real k = .5*pi;
I prefer to read

```
public:
protected:
private:
```

2023-10-30 20:11 UTC, lindsayad approved these changes

2023-10-30 20:14 UTC, nmnobre commented
@lindsayad Any thoughts on my observations regarding the extra error quadrature order input parameter?

2023-10-30 20:20 UTC, lindsayad commented
> As the default quadrature order is 2p+1, i.e. odd, adding an even number, m, as the extra order, is no better than just adding m-1.

Is this statement true for all quadrature rules or just those of Gaussian type? I believe it may not be generally true but @jwpeterson and @roystgnr have been talking a lot about quadrature lately and their knowledge base is deeper than mine

2023-10-31 00:13 UTC, merged

2023-10-31 18:38 UTC, roystgnr commented
Even for Gaussian quadrature that statement doesn't hold on triangles, tets, and prisms.  (Probably on pyramids, too, but pyramids are so crazy in general that we don't even try to do anything fancy there)

2023-11-03 16:29 UTC, nmnobre commented
You're obviously correct, I was stupidly blindfolded by edges, quads and hexes. :)