Allow all Petsc matrix types to proceed from a common base class
libMesh/libmesh pull request #3914
Opened 2024-08-01 18:01 UTC by lindsayad

And critically, always allow retrieving a PetscMatrix context from a PETSc mat. Eventually we may be able to remove the PetscMatrix from Mat constructors entirely. That would be good

This change was strongly suggested by the need to convert LinearSolver to be able to handle StaticCondensation

2024-08-01 19:52 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2362542/) on 1b9280e wanted to post the following:


## Coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>b0c2d7</th>
      <th colspan=4>#3914 1b9280</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>63.32%</td>
      <td>63.32%</td>
      <td>-0.01%</td>
      <td>67.03%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>71608</td>
      <td>71656</td>
      <td>+48</td>
      <td>244</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>41475</td>
      <td>41515</td>
      <td>+40</td>
      <td>120</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/libmesh/docs/PRs/3914/coverage_diff)

[Full coverage report](https://mooseframework.inl.gov/libmesh/docs/PRs/3914/coverage)

## Warnings

- New new line coverage rate 67.03% is less than the suggested 90.0%



This comment will be updated on new commits.

2024-08-12 15:09 UTC, roystgnr requested changes

2024-08-12 20:32 UTC, lindsayad commented on src/solvers/petsc_linear_solver.C
> +      }
I'm down 😆

2024-08-12 20:50 UTC, lindsayad commented on src/solvers/petscdmlibmeshimpl.C
> +  PetscMatrixBase<Number> * Jac = PetscMatrixBase<Number>::get_context(jac);
In the other case in `petsc_nonlinear_solver.C` the two are allowed to be `nullptr`. However, for the PC in `petsc_nonlinear_solver.C` I never allow reseat the pointer, so I added a `const` there

2024-08-12 21:30 UTC, moosebuild commented
Job [Test MOOSE clang](https://civet.inl.gov/job/2379545/) on 84661f7 : invalidated by @lindsayad

2024-08-12 21:30 UTC, moosebuild commented
Job [Test MOOSE GCC min](https://civet.inl.gov/job/2379547/) on 84661f7 : invalidated by @lindsayad

2024-08-12 21:30 UTC, moosebuild commented
Job [Test MOOSE debug](https://civet.inl.gov/job/2379546/) on 84661f7 : invalidated by @lindsayad

2024-08-12 21:31 UTC, moosebuild commented
Job [Test MOOSE min clang](https://civet.inl.gov/job/2379549/) on 84661f7 : invalidated by @lindsayad

2024-08-13 16:47 UTC, roystgnr approved these changes

2024-08-13 21:19 UTC, merged

2024-08-14 14:44 UTC, lindsayad commented
beautiful failed code

2024-08-14 17:54 UTC, lindsayad commented
it could be good to have such a macro in the future. For now, I think we have a good change in https://github.com/libMesh/libmesh/pull/3925